---

- name: simple-provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-2
    vpc_name: simple-vpc
    vpc_cidr_block: 10.210.0.0/16
    subnet_cidr_block: 10.210.1.0/24
    instance_image: ami-0a5a6128e65676ebb
    ec2_key_name: devos
    instance_type: t2.micro
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr_block}}"
      region: "{{aws_region}}"
      tags:
        Name: "{{vpc_name}}"
      tenancy: default
    register: result_vpc
    
  - name: Create subnet 
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{result_vpc.vpc.id}}"
      cidr: "{{subnet_cidr_block}}"
      region: "{{aws_region}}"
      az: "{{aws_region.availability_zones[0].zone_name}}"
      tags:
        Name: public
    register: result_subnet

  - name: Create Internet Gateway
    ec2_vpc_igw:
      vpc_id: "{{result_vpc.vpc.id}}"
      region: "{{aws_region}}"
      state: present
    register: result_igw
  
  - name: Set up public subnet route table
    ec2_vpc_route_table:
      vpc_id: "{{result_vpc.vpc.id}}"
      region: "{{aws_region}}"
      tags:
        Name: Public
      subnets:
        - "{{result_subnet.subnet.id}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{result_igw.gateway_id}}"
    register: result_route_table
    
  - name: Create security group
    ec2_group:
      name: allow tcp
      description: sg with rule descriptions
      vpc_id: "{{result_vpc.vpc.id}}"
#      profile: "{{ aws_profile }}"  
      region: "{{aws_region}}"
      rules:
        - proto: tcp
          ports:
          - 80
          - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on port 80
          
  - name: Create EC2
    ec2:
      key_name: "{{ec2_key_name}}"
      instance_type: "{{instance_type}}"
      image: "{{instance_image}}"
      region: "{{aws_region}}"
      wait: no
      group: allow tcp
      count: 1
      vpc_subnet_id: "{{result_subnet.subnet.id}}"
      assign_public_ip: yes
      instance_tags:
        Name: webserver
      