---

- name: simple-provisioning
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_region: ap-northeast-2
    vpc_name: simple-vpc
    vpc_cidr_block: 10.210.0.0/16
    subnet_cidr_block: 10.210.1.0/24
    instance_image: ami-0a5a6128e65676ebb
    ec2_key_name: devos
    instance_type: t2.micro
  tasks:
  - name: create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr_block}}"
      region: "{{aws_region}}"
      tags:
        Name: "{{vpc_name}}"
      tenancy: default
    register: result_vpc
    
  - name: Create subnet 
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{result_vpc.vpc.id}}"
      cidr: "{{subnet_cidr_block}}"
      region: "{{aws_region}}"
      tags:
        Name: public
    register: result_subnet
